TravelingDiaries/Controllers/ContentManagementController.cs
using Microsoft.AspNetCore.Mvc;
using TravelingDiaries.Models;

namespace TravelingDiaries.Controllers
{
    public class ContentManagementController : Controller
    {
        private readonly IPlaceRepository placeRepository;

        public ContentManagementController(IPlaceRepository placeRepository)
        {
            this.placeRepository = placeRepository;
        }
        //public IActionResult Index()
        //{
        //    return View();
        //}


        //CM page view
        public IActionResult CM()
        {
            var places= placeRepository.GetAllPlaces();
            return View(places);
        }


        //for the create form
        public IActionResult Create()
        {
            return View();
        }
     
        [HttpPost]
        [ValidateAntiForgeryToken]
        //to apply changes to db
        public IActionResult Create(Place place)
        {
            if (ModelState.IsValid) {
                placeRepository.AddPlace(place);            
            }
            TempData["Success"] = "Great! Created a new place.";
            return RedirectToAction("CM");
        }



        public IActionResult EditPlace(int id)
        {
            Place p=placeRepository.GetAllPlaces().FirstOrDefault(s => s.PlaceID == id);

            return View(p);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPlace(Place place)
        {
            if (ModelState.IsValid)
            {
                placeRepository.EditPlace(place);
            }
            TempData["Success"] = "Great! Edited the place.";
            return RedirectToAction("CM");
        }


        //To show the form of delete
        public IActionResult Delete(int id)
        {
            var place = placeRepository.GetAllPlaces().FirstOrDefault(s=>s.PlaceID==id);
            ViewData["ID"]= id;
            return View(place);
        }

        //to remove from the db
        public IActionResult DeletePlace(int? id)
        {
           placeRepository.RemovePlace(id);
            TempData["Success"] = "Great! Place has been deleted.";
            return RedirectToAction("CM");
        }
    }
}

TravelingDiaries/Views/ContentManagement/CM.cshtml
@model IEnumerable<TravelingDiaries.Models.Place>

@{
    ViewData["Title"] = "CM";
}
<style>
    body{  
        color:black;
               width:100%;
    min-height:100vh;
    padding:1%;
    background-image:url( https://images.pexels.com/photos/7582013/pexels-photo-7582013.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);
    background-position:center;
    background-size:cover;
    }
   
</style>


<partial name="_Notifications">
<table class="table table-light " style=" color:black;">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PlaceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShortDescription)
            </th>
      
            <th>
                @Html.DisplayNameFor(model => model.PackagePrice)
            </th>
            <th>Edit</th>
                <th>Delete</th>
        </tr>
    </thead>
    <tbody>

@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PlaceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShortDescription)
            </td>
         
            <td>
                @Html.DisplayFor(modelItem => item.PackagePrice)
            </td>
          <td>
            <button class="btn btn-warning">  <a asp-action="EditPlace" asp-route-id="@item.PlaceID" style="text-decoration:none;color:white;" >Edit</a></button>
          </td>
          
              <td>
                <button class="btn btn-danger">  <a style="text-decoration:none;color:white;" asp-action="Delete" asp-route-id="@item.PlaceID" asp-controller="ContentManagement">Delete</a></button>
            </td>
          
        </tr>
}
    </tbody>
</table>

TravelingDiaries/Views/ContentManagement/Create.cshtml
@model TravelingDiaries.Models.Place

@{
    ViewData["Title"] = "Create";
}
@if(TempData["Success"]!=null){
    <h2>@TempData["Success"]</h2>
}

<style>
    body{
    
/*        color:white;*/
               width:100%;
    min-height:100vh;
    padding:1%;
    background-image:url(https://images.pexels.com/photos/257352/pexels-photo-257352.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);
    background-position:center;
    background-size:cover;
      }
</style>
<h1>Welcome to Admin Dashboard</h1>

<h4>Here you can create a new place records.</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PlaceName" class="control-label"></label>
                <input  id="name" asp-for="PlaceName" class="form-control" />
                <span asp-validation-for="PlaceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image1" class="control-label"></label>
                <input asp-for="Image1" class="form-control" />
                <span asp-validation-for="Image1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image2" class="control-label"></label>
                <input asp-for="Image2" class="form-control" />
                <span asp-validation-for="Image2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image3" class="control-label"></label>
                <input asp-for="Image3" class="form-control" />
                <span asp-validation-for="Image3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PackagePrice" class="control-label"></label>
                <input asp-for="PackagePrice" class="form-control" />
                <span asp-validation-for="PackagePrice" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" onclick="return ValidateInput()" />
                  <button class="btn btn-success"><a style="color:white; text-decoration:none;" asp-action="Index">Back to List</a></button>
            </div>
            
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
function ValidateInput() 
{
    if (document.getElementById("name").value=="") 
    
    { 
        Swal.fire({
            icon: 'error',
            title: 'Oops...',
            text: 'Name is a required field!',
            footer: '<a href="#">Why do I have this issue?</a>'
        });
        return false;
    
    }
    return true;

}
    </script>
}

TravelingDiaries/Views/ContentManagement/Delete.cshtml
@model TravelingDiaries.Models.Place

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Place</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaceName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaceName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PackagePrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PackagePrice)
        </dd>
    </dl>
    
    <form asp-action="DeletePlace" asp-route-id="@ViewData["ID"]">
        <input type="hidden" asp-for="PlaceID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 

        <a asp-action="Index">Back to List</a>
    </form>
</div>

TravelingDiaries/Views/ContentManagement/DeletePlace.cshtml
@model TravelingDiaries.Models.Place

@{
    ViewData["Title"] = "DeletePlace";
}

<h1>DeletePlace</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Place</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaceName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaceName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PackagePrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PackagePrice)
        </dd>
    </dl>
    
    <form asp-action="DeletePlace" asp-route-id="">
        <input type="hidden" asp-for="PlaceID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TravelingDiaries/Views/ContentManagement/EditPlace.cshtml
@model TravelingDiaries.Models.Place

@{
    ViewData["Title"] = "EditPlace";
}

<h1>EditPlace</h1>

<h4>Place</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPlace" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PlaceID" />
            <div class="form-group">
                <label asp-for="PlaceName" class="control-label"></label>
                <input asp-for="PlaceName" class="form-control" />
                <span asp-validation-for="PlaceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image1" class="control-label"></label>
                <input asp-for="Image1" class="form-control" />
                <span asp-validation-for="Image1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image2" class="control-label"></label>
                <input asp-for="Image2" class="form-control" />
                <span asp-validation-for="Image2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image3" class="control-label"></label>
                <input asp-for="Image3" class="form-control" />
                <span asp-validation-for="Image3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PackagePrice" class="control-label"></label>
                <input asp-for="PackagePrice" class="form-control" />
                <span asp-validation-for="PackagePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" onclick="Success()" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
   
 @*   <script>
        function Success(){
        Swal.fire({
  position: 'top-end',
  icon: 'success',
  title: 'Your work has been saved',
  showConfirmButton: false,
  timer: 1500
});
            return true;
        }
    </script>*@


}