TravelingDiaries/Models/ShoppingCart.cs
using Microsoft.EntityFrameworkCore;

namespace TravelingDiaries.Models
{
    public class ShoppingCart
    {
       
        //We need to talk to the Db 
        private readonly AppDbContext appDbContext;
        public string ShoppingCartId { get; set; }


        //List of cartItems
        public List<ShoppingCartItem> ShoppingCartItems { get; set; }
        public ShoppingCart(AppDbContext appDbContext)
        {
            this.appDbContext = appDbContext;
        }

    
        public static ShoppingCart GetCart(IServiceProvider services)
        {
            ISession session = services.GetRequiredService<IHttpContextAccessor>()?
                .HttpContext.Session;

            var context = services.GetService<AppDbContext>();

            string cartId = session.GetString("CartId") ?? Guid.NewGuid().ToString();

            session.SetString("CartId", cartId);

            return new ShoppingCart(context) { ShoppingCartId = cartId };
        }










        //All normal methods needed
        //1.Method Add to basket
        public void AddToCart(Place place,int amount) {
            var shoppingCartItem =
            appDbContext.shoppingCartItems.SingleOrDefault(
                s => s.Place.PlaceID == place.PlaceID && s.ShoppingCartId == ShoppingCartId);
            //if it is the first time they are adding apple pie, then shoppingCartItem should be null


            if (shoppingCartItem == null)
            {
                //shoppingcartitem object and add it to customer bag
                shoppingCartItem = new ShoppingCartItem
                {
                    ShoppingCartId = ShoppingCartId,
                    Place = place,
                    Amount = 1
                };

                appDbContext.shoppingCartItems.Add(shoppingCartItem);
            }
            else
            {
                shoppingCartItem.Amount++;
            }

            appDbContext.SaveChanges();


        }



        
        public int RemoveFromCart(Place place)
        {
            var shoppingCartItem =
             appDbContext.shoppingCartItems.SingleOrDefault(
                 s => s.Place.PlaceID == place.PlaceID && s.ShoppingCartId == ShoppingCartId);

            int localValue = 0;

            if (shoppingCartItem != null) {
                if (shoppingCartItem.Amount > 1)
                {

                    shoppingCartItem.Amount--;
                    localValue = shoppingCartItem.Amount;
                }
                else
                {
                    appDbContext.shoppingCartItems.Remove(shoppingCartItem);
                }
               
            }
            appDbContext.SaveChanges();
            return localValue;





        }


        public List<ShoppingCartItem> GetShoppingCartItems()
        {

            return ShoppingCartItems ??
                (ShoppingCartItems = appDbContext.shoppingCartItems.Where(c => c.ShoppingCartId == ShoppingCartId).Include(s => s.Place).ToList());
         


        }

        public void ClearCart()
        {
            var cartItems = appDbContext.shoppingCartItems.Where(s => s.ShoppingCartId == ShoppingCartId);
            appDbContext.shoppingCartItems.RemoveRange(cartItems);

            appDbContext.SaveChanges();
        }

        public decimal GetShoppingCartTotal()
        {
            decimal amount = appDbContext.shoppingCartItems.Where(s => s.ShoppingCartId == ShoppingCartId).Select(s => s.Place.PackagePrice * s.Amount).Sum();
            return amount;

        }


    }
}

TravelingDiaries/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using TravelingDiaries.Models;

namespace TravelingDiaries.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;

        public OrderController(IOrderRepository orderRepository, ShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }


        //This is the form for details
        public IActionResult Checkout()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {


                ModelState.AddModelError("", "Your cart is empty add some pies");
            }
            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete",order);

            }

            return View(order);
        }


        public IActionResult CheckoutComplete(Order order)
        {

           
            return View(order);

        }
   

       
    }

    }

TravelingDiaries/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using TravelingDiaries.Models;
using TravelingDiaries.ViewModel;

namespace TravelingDiaries.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IPlaceRepository placeRepository;
        private readonly ShoppingCart _shoppingCart;
        private readonly AppDbContext appDbContext;


     
        public ShoppingCartController(IPlaceRepository placeRepository, ShoppingCart shoppingCart,AppDbContext appDb)
        {
            this.placeRepository = placeRepository;
            _shoppingCart = shoppingCart;
            appDbContext = appDb;
        }

        public ViewResult Index(string? Code)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            var code = appDbContext.Coupons.FirstOrDefault(s => s.CouponCode.Contains(Code));

            ViewBag.Couponvalue = 0;
            if (code != null)
            {
                ViewBag.Couponvalue = code.value;

            }
           
            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int id)
        {
            var selectedPie = placeRepository.GetAllPlaces().FirstOrDefault(p => p.PlaceID == id);

            if (selectedPie != null)
            {
                _shoppingCart.AddToCart(selectedPie, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int id)
        {
            var selectedPie = placeRepository.GetAllPlaces().FirstOrDefault(p => p.PlaceID == id);

            if (selectedPie != null)
            {
                _shoppingCart.RemoveFromCart(selectedPie);
            }
            return RedirectToAction("Index");
        }
        public IActionResult ClearCart() {
            _shoppingCart.ClearCart();
            return RedirectToAction("Index");
        }
    }
}

TravelingDiaries/Views/ShoppingCart/Index.cshtml
@using TravelingDiaries.ViewModel
@model ShoppingCartViewModel

<partial name="_Banner.cshtml">

<style>
    body {font-family: Verdana, sans-serif;
    background:rgba(255,255,255, 0.9);
}
</style>

<table class="table table-bordered table-striped">
    <thead>
    <tr>

        <th>Places</th>
        <th class="text-right">Price</th>
        <th class="text-right">Subtotal</th>
                
                   <th class="text-right">Member</th>
                <th class="text-right">Update Member</th>

    </tr>
    </thead>
    <tbody>
    @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
    {
        <tr>
            @*<td class="text-center">@line.Amount</td>*@
            <td class="text-left"> @line.Place.PlaceName</td>
            <td class="text-right">Rs @line.Place.PackagePrice</td>
            <td class="text-right">Rs
                @((line.Amount * line.Place.PackagePrice))
            </td>
                 
                  <td class="text-center"> @line.Amount</td>
         <td style="align-content:center">
             <a asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-Id="@line.Place.PlaceID" ><button class=" btn btn-danger" style="margin-left:33px" ><i class="bi bi-dash-circle-fill" style="display:inline-block"></i></button> </a>Rs
             <span>@line.Amount</span>
             <a asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-Id="@line.Place.PlaceID"><button class=" btn btn-success" ><i  class="bi bi-plus-circle-fill"></i></button> </a>

           
             
         </td> 
        </tr>
    }
    </tbody>
    <tfoot>
    <tr>
            @if (ViewBag.Couponvalue !=0)
            {

               
                 <td class="text-right">Amazing u are getting  discount of @ViewBag.Couponvalue %</td>

            }
            <td  class="text-right">Total:</td>
        <td class="text-right">
            @{
                        decimal amount = (Model.ShoppingCartTotal * (100 - ViewBag.Couponvalue) / 100);
                        
                    }
         Total Amount: Rs @amount
        </td>
    </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" asp-controller="Order" asp-action="Checkout">Checkout</a>
     <a class="btn btn-danger" asp-controller="ShoppingCart" asp-action="ClearCart">Clear Cart</a>
     <br></br>
     <form class="form-group">
           <input type="text"  placeholder="Write Coupon Code Here" name="Code"><br>
           <br></br>
         <button class="btn btn-warning" type="submit" asp-controller="ShoppingCart" asp-action="Index">Try Coupon</button>

     </form>
     
</div>
<br></br>

TravelingDiaries/Views/ShoppingCart/_Banner.cshtml
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box;}
body {font-family: Verdana, sans-serif;}
.mySlides {display: none;}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 500px;
  position: relative;
  margin: auto;
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.1s ease;
}

.active {
  background-color: #717171;
}



/*keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
/*media only screen and (max-width: 300px) {
  .text {font-size: 11px}
}*/
</style>
</head>
<body>

Rs
<div style="margin-left:22px;" class="slideshow-container" >

<div style="width:1029px; height:257;" class="mySlides ">
  <div class="numbertext">1 / 3</div>
  <img  src="https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/heroBannerImages/PilgrimageCampaign_1200X320_25July.jpg?crop=1200:320&downsize=1200:320" style="width:100%">

</div>

<div style="width:1029px; height:257"; class="mySlides ">
  <div class="numbertext">2 / 3</div>
  <img src="https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/heroBannerImages/1200x320_11111222.jpg?crop=1200:320&downsize=1200:320" style="width:100%">
</div>

<div style="width:1029px; height:257;" class="mySlides ">
  <div class="numbertext">3 / 3</div>
  <img src="https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/heroBannerImages/Wildlife_1200x320_22Aug.jpg?crop=1200:320&downsize=1200:320" style="width:100%">
</div>

</div>
<br>

<div style="text-align:center">
  <span class="dot"></span> 
  <span class="dot"></span> 
  <span class="dot"></span> 
</div>

<script>
let slideIndex = 0;
showSlides();

function showSlides() {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";  
  }
  slideIndex++;
  if (slideIndex > slides.length) {slideIndex = 1}    
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
  setTimeout(showSlides, 5000); // Change image every 2 seconds
}
</script>

<div>
 
</div>
</body>
</html> 