TravelingDiaries/Models/Hotel.cs
namespace TravelingDiaries.Models
{
    public class Hotel
    {
        public int HotelId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public int DestinationId { get; set; }
        public string ShortDescription { get; set; }

        public string Description { get; set; }

        public bool IsRoomEmpty { get; set; }


    }
}

TravelingDiaries/Controllers/HotelController.cs
using Microsoft.AspNetCore.Mvc;

namespace TravelingDiaries.Controllers
{
    public class HotelController : Controller
    {
        

        //to retrive all the Hotels
        //public IActionResult GetAllHotels()
        //{
        //    var hotels = hotelRepository.GetAllHotels();
        //    return View(hotels);

        //}


        //to get the details of single Hotel

        //public IActionResult HotelDetail(int? id)
        //{
        //    Hotel hotel = hotelRepository.HotelDetail(id);
        //    ViewData["ID"] = id;
        //    return View(hotel);

        //}


    }
}

TravelingDiaries/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using TravelingDiaries.Models;
using TravelingDiaries.ViewModel;

namespace TravelingDiaries.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IPlaceRepository placeRepository;
        private readonly ShoppingCart _shoppingCart;
        private readonly AppDbContext appDbContext;


     
        public ShoppingCartController(IPlaceRepository placeRepository, ShoppingCart shoppingCart,AppDbContext appDb)
        {
            this.placeRepository = placeRepository;
            _shoppingCart = shoppingCart;
            appDbContext = appDb;
        }

        public ViewResult Index(string? Code)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            var code = appDbContext.Coupons.FirstOrDefault(s => s.CouponCode.Contains(Code));

            ViewBag.Couponvalue = 0;
            if (code != null)
            {
                ViewBag.Couponvalue = code.value;

            }
           
            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int id)
        {
            var selectedPie = placeRepository.GetAllPlaces().FirstOrDefault(p => p.PlaceID == id);

            if (selectedPie != null)
            {
                _shoppingCart.AddToCart(selectedPie, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int id)
        {
            var selectedPie = placeRepository.GetAllPlaces().FirstOrDefault(p => p.PlaceID == id);

            if (selectedPie != null)
            {
                _shoppingCart.RemoveFromCart(selectedPie);
            }
            return RedirectToAction("Index");
        }
        public IActionResult ClearCart() {
            _shoppingCart.ClearCart();
            return RedirectToAction("Index");
        }
    }
}

TravelingDiaries/Views/Hotel/GetAllHotels.cshtml
@*@model IEnumerable<TripAdvisor.Models.Hotel>

@{
    ViewData["Title"] = "GetAllHotels";
}

 <style>
        body{
             background-image: url("https://img.freepik.com/free-photo/closeup-concrete-wall-texture-background_1017-24490.jpg?w=2000");
 background-color: #cccccc;
           
        
        }
    </style>

<h1>Choose Your Luxirious Stay !!</h1>

<body>
    @foreach(var hotel in Model){

<div class="card border-danger mb-3" style="max-width: 20rem; display:inline-block;margin:100px;">
  <img class="card-img-top" src="@hotel.ImageUrl" alt="Card image cap" style="height:213px">
  <div class="card-body">
    <h5 class="card-title"><strong>@hotel.Name</strong></h5>
   <div style=" height:96px;width:288px;"><p class="card-text">@hotel.ShortDescription</p></div> 
    <h6 class="card-text"><strong> Rs:@hotel.Price</strong></h6>

    <a asp-controller="Hotel" asp-route-id="@hotel.HotelId" asp-action="HotelDetail" class="btn btn-primary">Know More</a>
  </div>
</div>



}
</body>



@*
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DestinationId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsRoomEmpty)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DestinationId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsRoomEmpty)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.HotelId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.HotelId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.HotelId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
*@

TravelingDiaries/Views/Hotel/HotelDetail.cshtml
@*@model TripAdvisor.Models.Hotel

@{
    ViewData["Title"] = "HotelDetail";
}

<style>
        body{
             background-image: url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYqKOT9rNEdBJ6_FeFyBEeOX0G769FERYXPZEOTKrVbw&s");
 background-color: #cccccc;  
        }
    </style>

    <div>
  <h2>@Model.Name</h2>
  <div class="thumbnail">
    <img alt="@Model.Name"  width = "800px" height = "500px" src="@Model.ImageUrl">
    <div class="caption-full">
        <h3 class="pull-right">Rs.@Model.Price</h3>
        
        <h4>@Model.ShortDescription</h4>
        <p>@Model.Description</p>


   <button type="button" class="btn btn-dark"><a  style="text-decoration:none; color:white"; asp-action="AddToShoppingCart" asp-controller="ShoppingCart" asp-route-id=@ViewData["ID"]>Book Now</a></button>

   <button type="button" class="btn btn-dark">   <a style="text-decoration:none; color:white;"  asp-action="Index" asp-controller="Home">Back to List</a></button>
</div>

  *@