TravelingDiaries/Models/Place.cs
namespace TravelingDiaries.Models
{
    public class Place
    {
        public int PlaceID { get; set; }
        public string PlaceName { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Image1 { get; set; }

        public string Image2 { get; set; }

        public string Image3 { get; set; }

        public int PackagePrice { get; set; }

        
     
    }
}

TravelingDiaries/Controllers/PlaceController.cs
using Microsoft.AspNetCore.Mvc;
using TravelingDiaries.Models;

namespace TravelingDiaries.Controllers
{
    public class PlaceController : Controller
    {
        private readonly IPlaceRepository placeRepository;

        public PlaceController(IPlaceRepository placeRepository)
        {
            this.placeRepository = placeRepository;
        }


        //to retrive all the places.
        public IActionResult GetAllPlaces() {
            var places=placeRepository.GetAllPlaces();
            return View(places);

        }
        //to get the details of single place
        public IActionResult PlaceDetail(int? id)
        {
            Place place = placeRepository.PlaceDetail(id);
            ViewData["ID"]= id;
            return View(place);

        }


    }
}

TravelingDiaries/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using TravelingDiaries.Models;
using TravelingDiaries.ViewModel;

namespace TravelingDiaries.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IPlaceRepository placeRepository;
        private readonly ShoppingCart _shoppingCart;
        private readonly AppDbContext appDbContext;


     
        public ShoppingCartController(IPlaceRepository placeRepository, ShoppingCart shoppingCart,AppDbContext appDb)
        {
            this.placeRepository = placeRepository;
            _shoppingCart = shoppingCart;
            appDbContext = appDb;
        }

        public ViewResult Index(string? Code)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            var code = appDbContext.Coupons.FirstOrDefault(s => s.CouponCode.Contains(Code));

            ViewBag.Couponvalue = 0;
            if (code != null)
            {
                ViewBag.Couponvalue = code.value;

            }
           
            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int id)
        {
            var selectedPie = placeRepository.GetAllPlaces().FirstOrDefault(p => p.PlaceID == id);

            if (selectedPie != null)
            {
                _shoppingCart.AddToCart(selectedPie, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int id)
        {
            var selectedPie = placeRepository.GetAllPlaces().FirstOrDefault(p => p.PlaceID == id);

            if (selectedPie != null)
            {
                _shoppingCart.RemoveFromCart(selectedPie);
            }
            return RedirectToAction("Index");
        }
        public IActionResult ClearCart() {
            _shoppingCart.ClearCart();
            return RedirectToAction("Index");
        }
    }
}

TravelingDiaries/Views/Place/GetAllPlaces.cshtml
@model IEnumerable<TravelingDiaries.Models.Place>


    <style>
        body{
             background-image: url("https://images.pexels.com/photos/931018/pexels-photo-931018.jpeg");
 background-color: #cccccc;


           
        
        }
    </style>


<body>
    @foreach(var place in Model){

<div class="card border-danger mb-3" style="max-width: 20rem; display:inline-block;margin:20px;">
  <img class="card-img-top" src="@place.Image" alt="Card image cap" style="height:213px">
  <div class="card-body">
    <h5 class="card-title"><strong>@place.PlaceName</strong></h5>
    <hr>
   <div style=" height:96px;width:288px;"><p class="card-text">@place.ShortDescription</p></div> 
   <br>
   <br>
   <hr>
    <h6 class="card-text"><strong> Rs:@place.PackagePrice</strong></h6>
    <hr>
    <a asp-controller="Place" asp-route-id="@place.PlaceID" asp-action="PlaceDetail" class="btn btn-secondary">See More</a>
  </div>
</div>



}
</body>

TravelingDiaries/Views/Place/PlaceDetail.cshtml
@model TravelingDiaries.Models.Place

@{
    ViewData["Title"] = "PlaceDetail";
}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>

* {box-sizing: border-box;}
body {font-family: Verdana, sans-serif;
 
  background-image: linear-gradient(#538FFB, #5737D6);
.mySlides {display: none;}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 800px;
  position: relative;
  margin: auto;
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active {
  background-color: #717171;
}



/*keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
/*media only screen and (max-width: 300px) {
  .text {font-size: 11px}
}*/

h4{
}
</style>
</head>
<body>


        <h4 style="background:white;font-size:50px;text-align:center;color:black;"><b>@Model.PlaceName</b></h4>
<div class="slideshow-container" style="width:500px; border:10px solid ;">

<div class="mySlides ">

  <img src="@Model.Image" style="width:100%">

</div>

<div class="mySlides ">
  
  <img src="@Model.Image1" style="width:100%">
</div>

<div class="mySlides ">

  <img src="@Model.Image2" style="width:100%">
</div>

</div>
<br>

<div style="text-align:center">
  <span class="dot"></span> 
  <span class="dot"></span> 
  <span class="dot"></span> 
</div>



<script>


let slideIndex = 0;
showSlides();

function showSlides() {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";  
  }
  slideIndex++;
  if (slideIndex > slides.length) {slideIndex = 1}    
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
  setTimeout(showSlides, 2000); // Change image every 2 seconds
}
</script>



<div>

    <hr />
    <dl class="row" style="background:black;color:white">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaceName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaceName)
        </dd>

        <hr />
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>

        <hr />
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    <hr />
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PackagePrice)
        </dt>
        <dd class = "col-sm-10">     
            Rs:@Html.DisplayFor(model => model.PackagePrice)
        </dd>
    </dl>
   <button type="button" class="btn btn-warning"><a  style="text-decoration:none; color:white"; asp-action="AddToShoppingCart" asp-controller="ShoppingCart" asp-route-id=@ViewData["ID"]>Buy Now</a></button>

   <button type="button" class="btn btn-info">   <a style="text-decoration:none; color:white;"  asp-action="Index" asp-controller="Home">Back to List</a></button>
</div>
<div>
 
</div>
</body>
</html> 